#!/bin/sh
# agit:pre-push guard. Generated by agit. Do not edit by hand.
#
# This is a guardrail, not a security boundary: git push --no-verify skips it and
# so does any process that writes the push token. GitHub rulesets are the real
# backstop. Run agit doctor to see which layers are actually active.
set -e

protected="{{DEFAULT_BRANCH}}"
token_file=$(git rev-parse --git-path agit-allow-push)

if [ ! -f "$token_file" ]; then
  echo "agit: git push is blocked. Use agit finish <task-id>." >&2
  exit 1
fi

token=$(cat "$token_file")
rm -f "$token_file"

zero=0000000000000000000000000000000000000000
while read local_ref local_sha remote_ref remote_sha
do
  branch=${remote_ref#refs/heads/}
  if [ "$branch" = "$protected" ] || [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
    echo "agit: push to $branch is blocked." >&2
    exit 1
  fi
  if [ "$local_sha" != "$token" ]; then
    echo "agit: the push token does not match the pushed commit." >&2
    echo "Use agit finish <task-id>." >&2
    exit 1
  fi
  if [ -n "$remote_sha" ] && [ "$remote_sha" != "$zero" ] && [ "$local_sha" != "$zero" ]; then
    if ! git merge-base --is-ancestor "$remote_sha" "$local_sha"; then
      echo "agit: force push is blocked." >&2
      exit 1
    fi
  fi
done

exit 0
