#!/bin/sh
# agit guard adapter for cursor tool-call hooks. Generated by agit.
# Resolves agit locally and never installs from the network.
# If agit cannot be found the guard stays out of the way; agit doctor reports it.
set -u

root=$(cd "$(dirname "$0")/../.." && pwd)

if [ -x "$root/node_modules/.bin/agit" ]; then
  exec "$root/node_modules/.bin/agit" guard --vendor cursor
fi

if command -v agit >/dev/null 2>&1; then
  exec agit guard --vendor cursor
fi

printf '%s\n' '{"permission": "allow"}'
exit 0
