import { execFile } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";
import { fetch, getConfig, remoteUrl, setConfig, setRemoteUrl, unsetConfig } from "./git.js";
import { MIRROR_DIR } from "./paths.js";
import { agitRoot } from "./root.js";

const execFileAsync = promisify(execFile);

async function gitAt(gitDir, args, { allowFail = false } = {}) {
  try {
    const { stdout } = await execFileAsync("git", args, { cwd: gitDir, encoding: "utf8" });
    return stdout.replace(/\n$/, "");
  } catch (error) {
    if (allowFail) {
      return null;
    }
    throw error;
  }
}

export function mirrorPath(root) {
  return resolve(root, MIRROR_DIR);
}

export async function resolveMirrorDir(cwd) {
  try {
    return mirrorPath(await agitRoot(cwd));
  } catch {
    return mirrorPath(cwd);
  }
}

export async function publishUrl(cwd, profile) {
  return (await getConfig(cwd, "agit.pushUrl")) || profile?.repo?.url || null;
}

export async function isolationEnabled(cwd) {
  return (await getConfig(cwd, "agit.isolate")) === "true";
}

export function normalizeGitUrl(url) {
  if (!url) {
    return "";
  }
  let value = String(url).trim().replace(/^file:\/\//, "").replace(/\/$/, "");
  if (!value.startsWith("/") && !value.startsWith(".")) {
    return value;
  }
  const absolute = resolve(value);
  try {
    return existsSync(absolute) ? realpathSync(absolute) : absolute;
  } catch {
    return absolute;
  }
}

export function isMirrorUrl(cwd, url) {
  if (!url) {
    return false;
  }
  const normalized = normalizeGitUrl(url);
  if (normalized === normalizeGitUrl(mirrorPath(cwd))) {
    return true;
  }
  return /(?:^|\/)\.agit\/mirror\.git$/.test(normalized);
}

export async function originPointsAtMirror(cwd) {
  return isMirrorUrl(cwd, await remoteUrl(cwd));
}

function receiveHook(defaultBranch) {
  return `#!/bin/sh
# agit:mirror-receive. Generated by agit isolate.
# The default branch is a cache of GitHub. Unpublished work belongs on agit/* branches.
set -e
protected="${defaultBranch}"
while read oldrev newrev ref
do
  branch=\${ref#refs/heads/}
  if [ "$branch" = "$protected" ]; then
    echo "agit: the local mirror rejects pushes to $protected." >&2
    echo "The default branch is synced from the real remote by agit start / finish." >&2
    exit 1
  fi
done
exit 0
`;
}

async function installReceiveHook(dir, defaultBranch) {
  const path = resolve(dir, "hooks/pre-receive");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, receiveHook(defaultBranch));
  chmodSync(path, 0o755);
  return path;
}

async function listRefs(gitDir, prefix) {
  const output = await gitAt(gitDir, ["for-each-ref", "--format=%(refname)%09%(objectname)", prefix], {
    allowFail: true,
  });
  if (!output) {
    return [];
  }
  return output.split("\n").filter(Boolean).map((line) => {
    const [ref, sha] = line.split("\t");
    return { ref, sha, name: ref.slice(prefix.length) };
  });
}

async function isAncestorAt(gitDir, ancestor, descendant) {
  const result = await gitAt(gitDir, ["merge-base", "--is-ancestor", ancestor, descendant], { allowFail: true });
  return result !== null;
}

// Pull GitHub (or the stored push URL) into the mirror. Team branches track the
// remote. Unpublished agit/* branches on the mirror are left alone.
export async function syncMirror(cwd, profile) {
  const dir = await resolveMirrorDir(cwd);
  const url = await publishUrl(cwd, profile);
  if (!existsSync(dir) || !url) {
    return { synced: false };
  }

  const prefix = profile.workflow?.branch_prefix ?? "agit/";
  await gitAt(dir, ["fetch", "--prune", url, "+refs/heads/*:refs/agit-sync/*"]);

  const incoming = await listRefs(dir, "refs/agit-sync/");
  const local = new Map((await listRefs(dir, "refs/heads/")).map((item) => [item.name, item.sha]));

  for (const ref of incoming) {
    const current = local.get(ref.name);
    const keepUnpublished = ref.name.startsWith(prefix) && current && !(await isAncestorAt(dir, current, ref.sha));
    if (!keepUnpublished) {
      await gitAt(dir, ["update-ref", `refs/heads/${ref.name}`, ref.sha]);
    }
    await gitAt(dir, ["update-ref", "-d", ref.ref], { allowFail: true });
  }

  const head = profile.repo?.default_branch;
  if (head) {
    await gitAt(dir, ["symbolic-ref", "HEAD", `refs/heads/${head}`], { allowFail: true });
  }

  await fetch(cwd);
  return { synced: true };
}

export async function updateMirrorBranch(cwd, branch, sha) {
  const dir = await resolveMirrorDir(cwd);
  if (!existsSync(dir)) {
    return;
  }
  // The object lives in the work tree until we fetch it; update-ref alone cannot
  // create a ref to a SHA the mirror has never seen.
  await gitAt(dir, ["fetch", cwd, `+${sha}:refs/heads/${branch}`]);
}

export async function inspectIsolation(cwd, profile) {
  const origin = await remoteUrl(cwd);
  const url = await publishUrl(cwd, profile);
  const flagged = await isolationEnabled(cwd);
  const dir = await resolveMirrorDir(cwd);
  const mirror = existsSync(dir);
  const originIsMirror = isMirrorUrl(cwd, origin) || isMirrorUrl(dir, origin);
  const isolated = Boolean(flagged && originIsMirror && url && !isMirrorUrl(cwd, url));

  return {
    isolated,
    flagged,
    origin,
    push_url: url,
    mirror,
    origin_is_mirror: originIsMirror,
  };
}

export async function enableIsolation(cwd, profile) {
  const origin = await remoteUrl(cwd);
  if (!origin) {
    throw new Error("No origin remote to isolate.");
  }

  const dir = await resolveMirrorDir(cwd);
  const already = isMirrorUrl(cwd, origin) || isMirrorUrl(dir, origin);
  const url = already ? await publishUrl(cwd, profile) : origin;
  if (!url) {
    throw new Error("Cannot tell where the real remote is.");
  }

  mkdirSync(dirname(dir), { recursive: true });
  if (!existsSync(dir)) {
    await execFileAsync("git", ["clone", "--bare", url, dir], { encoding: "utf8" });
  }

  await installReceiveHook(dir, profile.repo?.default_branch ?? "main");
  if (!already) {
    await setRemoteUrl(cwd, "origin", dir);
  }

  await setConfig(cwd, "agit.isolate", "true");
  await setConfig(cwd, "agit.pushUrl", url);
  await syncMirror(cwd, { ...profile, repo: { ...profile.repo, url: profile.repo.url ?? url } });
  return { mirror: dir, push_url: url, already };
}

export async function disableIsolation(cwd, profile) {
  const url = await publishUrl(cwd, profile);
  if (!url) {
    throw new Error("agit.pushUrl is not set; cannot restore origin.");
  }
  if (await originPointsAtMirror(cwd)) {
    await setRemoteUrl(cwd, "origin", url);
  }
  await unsetConfig(cwd, "agit.isolate");
  return { origin: url };
}
